version: "0.1"
user: sumits130493
key: DKmMR6S5jFMQHa8baw1TewJ0Ky1jw0wqbsYoNEzBHHLxhn2dWF
testSuites: []
pre: [npm install playwright --save-exact, pip install -r requirement.txt --cache-dir CacheDir, playwright install]
preDirectives:
    commands: [npm install playwright --save-exact, pip install -r requirement.txt --cache-dir CacheDir, playwright install]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
env:
    TARGET_OS: Windows 10
jobLabel:
    - playwright-pytest
    - win
    - autosplit
runson: win
autosplit: true
concurrency: 1
testDiscovery:
    command: grep -lr 'def' *.py
    mode: static
    type: raw
testDiscoveryResult:
    - test_app.py
testDiscoveryResult2D:
    - - test_app.py
testRunnerCommand: pytest $test
globalTimeout: 90
tunnelOpts:
    testsPerTunnel: 10
testSuiteTimeout: 90
testSuiteStep: 90
cacheDirectories:
    - CacheDir
cacheKey: '{{ checksum "requirement.txt" }}'
retryOnFailure: true
maxRetries: 1
jobID: 50998e07-3cea-415c-95a6-e29499580abd
codeDirectory: hyperexecute-playwright-pypi-sample
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: ""
        testSuitePath: ""
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices: []
        deviceSelectionStrategy: ""
        appId: ""
        testSuiteAppId: ""
        xcTestPlanId: ""
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: null
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        resignApp: true
        minorOsVersion: false
        playwrightRD: false
        mobileDC: null
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
        mitmProxy: false
        networkHar: false
        artifacts: false
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
testType: playwright
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: false
platformConfig: null
differentialUpload:
    enabled: false
    ttlHours: null
    forcedDisabled: false
project:
    id: ""
    name: ""
    type: default
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
testDiscoveryResultV3: []
storageType: ""
localHTTPProxy: ""
regionConfig: []
waitForArtefactsUpload: false
unzipPayload: false
accessibilityJob: false
slackChannel: ""
